export default {
    cross: {
        areaNumber: "test",
        checked: false,
        checker: "",
        code: "55555",
        completed: true,
        controlType: 1,
        coordSystem: "BD09",
        createTime: "20200617130612274",
        deleted: false,
        grade: 11,
        id: "a7f53f0d59d445e295f11b2ad4521090",
        latitude: 22.566604888070554,
        longitude: 114.13338915799285,
        name: "55555",
        netWork: 1,
        number: "1",
        principal: "",
        remark: "",
        roads: [
            {
                angle: 0,
                auxiliary: false,
                crossId: "a7f53f0d59d445e295f11b2ad4521090",
                crossUpdateTime: "20200708175625327",
                direction: 4,
                entrance: {
                    canalizationStatus: 0,
                    canalizations: [],
                    facilities: [],
                    facilityStatus: 0,
                    forbiddenFlag: 0,
                    id: "86a80ff46875492b88df094d40c4978b",
                    innovateType: "0",
                    laneStatus: 0,
                    lanes: [
                        {
                            direction: 1,
                            id: "3e539526e5cf4e999f6fc9c97a3c69bc",
                            number: "1",
                            preDirection: 0,
                            sourceId: "86a80ff46875492b88df094d40c4978b",
                            type: 2,
                            width: 4,
                        },
                        {
                            direction: 3,
                            number: "4",
                            type: 4,
                            width: 3.5,
                        },
                        {
                            direction: 3,
                            number: "4",
                            type: 1,
                            width: 3.5,
                        },
                        // {
                        //     direction: 3,
                        //     number: "4",
                        //     type: 4,
                        //     width: 3.5,
                        // },
                        // {
                        //     direction: 3,
                        //     number: "4",
                        //     type: 5,
                        //     width: 3.5,
                        // },
                        // {
                        //     direction: 3,
                        //     number: "4",
                        //     type: 6,
                        //     width: 3.5,
                        // },
                    ],
                    lightStatus: 0,
                    lights: [],
                    roadId: "ede515c5864d4ec9b6add4108eba9710",
                    sectionLaneCount: 3,
                    stationStatus: 0,
                    stations: [],
                },
                exit: {
                    facilities: [],
                    facilityStatus: 0,
                    id: "022141fdd4704294bd97f14d3917fb13",
                    laneStatus: 0,
                    lanes: [
                        {
                            direction: 2,
                            id: "21616c5805184890af4bd2cabda02cf3",
                            number: "1",
                            preDirection: 0,
                            sourceId: "022141fdd4704294bd97f14d3917fb13",
                            width: 3.5,
                        },
                        {
                            direction: 2,
                            id: "9c5c7430f33d45d8bf46a9a2b8c8638d",
                            number: "2",
                            preDirection: 0,
                            sourceId: "022141fdd4704294bd97f14d3917fb13",
                            width: 3.5,
                        },
                        {
                            direction: 2,
                            id: "15a5ba3d50ef43b2b9a2920e83eddcff",
                            number: "3",
                            preDirection: 0,
                            sourceId: "022141fdd4704294bd97f14d3917fb13",
                            width: 3.5,
                        },
                    ],
                    roadId: "ede515c5864d4ec9b6add4108eba9710",
                    stationStatus: 0,
                    stations: [],
                },
                id: "ede515c5864d4ec9b6add4108eba9710",
                index: 0,
                laneCount: 0,
                medianType: 3,
                medianWidth: 2,
                name: "分支1",
                sidewalk: 2,
            },
            {
                angle: 90,
                auxiliary: false,
                crossId: "a7f53f0d59d445e295f11b2ad4521090",
                crossUpdateTime: "20200708175625327",
                direction: 1,
                entrance: {
                    canalizationStatus: 0,
                    canalizations: [],
                    facilities: [],
                    facilityStatus: 0,
                    forbiddenFlag: 0,
                    id: "449cce023725493daa111c1117f5d04c",
                    innovateType: "0",
                    laneStatus: 0,
                    lanes: [
                        {
                            direction: 1,
                            id: "354e595f0c6a4d0e88b18b0c68859c17",
                            number: "1",
                            preDirection: 0,
                            sourceId: "449cce023725493daa111c1117f5d04c",
                            type: "1",
                            width: 3.5,
                        },
                        {
                            direction: 2,
                            id: "27945721498c4d00b1256d5a164d977b",
                            number: "2",
                            preDirection: 0,
                            sourceId: "449cce023725493daa111c1117f5d04c",
                            type: "1",
                            width: 3.5,
                        },
                        {
                            direction: 3,
                            id: "e125d7547a61425386676443b11212eb",
                            number: "3",
                            preDirection: 0,
                            sourceId: "449cce023725493daa111c1117f5d04c",
                            type: "1",
                            width: 3.5,
                        },
                    ],
                    lightStatus: 0,
                    lights: [],
                    roadId: "93abc7f6fd434de6aeba58f0c2b951e1",
                    sectionLaneCount: 3,
                    stationStatus: 0,
                    stations: [],
                },
                exit: {
                    facilities: [],
                    facilityStatus: 0,
                    id: "98513b97391f452483af6f0349e84ed0",
                    laneStatus: 0,
                    lanes: [
                        {
                            direction: 2,
                            id: "976ba8d925a348bc97818a02f42af71c",
                            number: "1",
                            preDirection: 0,
                            sourceId: "98513b97391f452483af6f0349e84ed0",
                            width: 3.5,
                        },
                        {
                            direction: 2,
                            id: "3bee0afddc4a4adcac1619a21400995d",
                            number: "2",
                            preDirection: 0,
                            sourceId: "98513b97391f452483af6f0349e84ed0",
                            width: 3.5,
                        },
                        {
                            direction: 2,
                            id: "607d748edd844a10be35ded513ef2477",
                            number: "3",
                            preDirection: 0,
                            sourceId: "98513b97391f452483af6f0349e84ed0",
                            width: 3.5,
                        },
                    ],
                    roadId: "93abc7f6fd434de6aeba58f0c2b951e1",
                    stationStatus: 0,
                    stations: [],
                },
                id: "93abc7f6fd434de6aeba58f0c2b951e1",
                index: 1,
                laneCount: 0,
                medianType: 3,
                medianWidth: 2,
                name: "分支2",
                sidewalk: 2,
            },
            {
                angle: 180,
                auxiliary: false,
                crossId: "a7f53f0d59d445e295f11b2ad4521090",
                crossUpdateTime: "20200708175625327",
                direction: 3,
                entrance: {
                    canalizationStatus: 0,
                    canalizations: [],
                    facilities: [],
                    facilityStatus: 0,
                    forbiddenFlag: 0,
                    id: "5774082d81b340d2bf8e35d9c734267e",
                    innovateType: "0",
                    laneStatus: 0,
                    lanes: [
                        {
                            direction: 1,
                            id: "bc1b63406f804e09af04f47e89ad71b7",
                            number: "1",
                            preDirection: 0,
                            sourceId: "5774082d81b340d2bf8e35d9c734267e",
                            type: "1",
                            width: 3.5,
                        },
                        {
                            direction: 2,
                            id: "4391210728244e9ab0b857b4e9f7b802",
                            number: "2",
                            preDirection: 0,
                            sourceId: "5774082d81b340d2bf8e35d9c734267e",
                            type: "1",
                            width: 3.5,
                        },
                        {
                            direction: 3,
                            id: "0e0a9798b5d7491b85bb0599020a5482",
                            number: "3",
                            preDirection: 0,
                            sourceId: "5774082d81b340d2bf8e35d9c734267e",
                            type: "1",
                            width: 3.5,
                        },
                    ],
                    lightStatus: 0,
                    lights: [],
                    roadId: "c227579b43514a05b3f43215e0c88818",
                    sectionLaneCount: 3,
                    stationStatus: 0,
                    stations: [],
                },
                exit: {
                    facilities: [],
                    facilityStatus: 0,
                    id: "797c4bb830c04c05bf2e2dea18bb0d7b",
                    laneStatus: 0,
                    lanes: [
                        {
                            direction: 2,
                            id: "fde12db0c3a24374a93dc010391f0b40",
                            number: "1",
                            preDirection: 0,
                            sourceId: "797c4bb830c04c05bf2e2dea18bb0d7b",
                            width: 3.5,
                        },
                        {
                            direction: 2,
                            id: "27587030b9ac4b84b232d3235d9a94e7",
                            number: "2",
                            preDirection: 0,
                            sourceId: "797c4bb830c04c05bf2e2dea18bb0d7b",
                            width: 3.5,
                        },
                        {
                            direction: 2,
                            id: "c382886d07354d969f47a53674a0b6fc",
                            number: "3",
                            preDirection: 0,
                            sourceId: "797c4bb830c04c05bf2e2dea18bb0d7b",
                            width: 3.5,
                        },
                    ],
                    roadId: "c227579b43514a05b3f43215e0c88818",
                    stationStatus: 0,
                    stations: [],
                },
                id: "c227579b43514a05b3f43215e0c88818",
                index: 2,
                laneCount: 0,
                medianType: 3,
                medianWidth: 2,
                name: "分支3",
                sidewalk: 2,
            },
            {
                "medianType": 3,
                "sidewalk": 2,
                "medianWidth": 2,
                "name": "分支4",
                "direction": 2,
                "angle": 270,
                "index": 3,
                "auxiliary": false,
                "exit": {
                    "lanes": [{
                        "number": "1",
                        "width": 3.5,
                        "direction": 2
                    }, {
                        "number": "2",
                        "width": 3.5,
                        "direction": 2
                    },
                    {
                        "number": "3",
                        "width": 3.5,
                        "direction": 2
                    }
                    ]
                },
                "entrance": {
                    "innovateType": "0",
                    "lanes": [{
                        "number": "1",
                        "width": 3.5,
                        "direction": 1,
                        "preDirection": 0,
                        type: 1
                    }, {
                        "number": "2",
                        "width": 3.5,
                        "direction": 2,
                        "preDirection": 0,
                        type: 1
                    },
                    {
                        "number": "3",
                        "width": 3.5,
                        "direction": 3,
                        "preDirection": 0,
                        type: 1
                    },
                    ],
                    "canalizations": [],
                    "lights": [],
                    "signalGroups": [{
                        "id": "",
                        "crossId": "",
                        "number": 5,
                        "name": "信号1",
                        "type": 3,
                        "direction": 2,
                        "controlMode": 1,
                        "laneId": "",
                        "index": "",
                        "lightType": 2,
                        "flowDirection": 17,
                        "entranceId": "",
                        "minGreenTime": 10,
                        "maxGreenTime1": 30,
                        "maxGreenTime2": 40,
                        "loseTransitiveType1": 0x22,
                        "loseTransitiveTime1": 12,
                        "loseTransitiveType2": 0x10,
                        "loseTransitiveTime2": 5,
                        "securityGreenTime": 5,
                        "securityFlashTime": 8,
                        "securityYellowTime": "",
                        "securityRedTime": 5,
                        "channels": [{
                            "signalGroupId": "",
                            "number": 5,
                            "type": 0
                        }]
                    }, {
                        "id": "",
                        "crossId": "",
                        "number": 6,
                        "name": "",
                        "type": 1,
                        "direction": 2,
                        "controlMode": 1,
                        "laneId": "",
                        "index": 1,
                        "lightType": 2,
                        "flowDirection": 1,
                        "entranceId": "",
                        "minGreenTime": 10,
                        "maxGreenTime1": 30,
                        "maxGreenTime2": 40,
                        "loseTransitiveType1": 0x22,
                        "loseTransitiveTime1": 3,
                        "loseTransitiveType2": 0x30,
                        "loseTransitiveTime2": 3,
                        "loseTransitiveType3": 0x10,
                        "loseTransitiveTime3": 2,
                        "securityGreenTime": 5,
                        "securityFlashTime": 2,
                        "securityYellowTime": 2,
                        "securityRedTime": 2,
                        "channels": [
                            {
                                "signalGroupId": "",
                                "number": 6,
                                "type": 0
                            }]
                    }, {
                        "id": "",
                        "crossId": "",
                        "number": 7,
                        "name": "",
                        "type": 1,
                        "direction": 2,
                        "controlMode": 1,
                        "laneId": "",
                        "index": 1,
                        "lightType": 2,
                        "flowDirection": 2,
                        "entranceId": "",
                        "minGreenTime": 10,
                        "maxGreenTime1": 30,
                        "maxGreenTime2": 40,
                        "loseTransitiveType1": 0x22,
                        "loseTransitiveTime1": 3,
                        "loseTransitiveType2": 0x30,
                        "loseTransitiveTime2": 3,
                        "loseTransitiveType3": 0x10,
                        "loseTransitiveTime3": 2,
                        "securityGreenTime": 5,
                        "securityFlashTime": 2,
                        "securityYellowTime": 2,
                        "securityRedTime": 2,
                        "channels": [
                            {
                                "signalGroupId": "",
                                "number": 7,
                                "type": 0
                            }]
                    }, {
                        "id": "",
                        "crossId": "",
                        "number": 8,
                        "name": "",
                        "type": 3,
                        "direction": 2,
                        "controlMode": "",
                        "laneId": "",
                        "index": "",
                        "lightType": "",
                        "flowDirection": 18,
                        "entranceId": "",
                        "minGreenTime": 10,
                        "maxGreenTime1": 30,
                        "maxGreenTime2": 40,
                        "loseTransitiveType1": 0x22,
                        "loseTransitiveTime1": 12,
                        "loseTransitiveType2": 0x10,
                        "loseTransitiveTime2": 5,
                        "securityGreenTime": 5,
                        "securityFlashTime": 8,
                        "securityYellowTime": "",
                        "securityRedTime": 5,
                        "channels": [
                            {
                                "signalGroupId": "",
                                "number": 8,
                                "type": 0
                            }]
                    }]
                }
            }
        ],
        shape: 4,
        status: 0,
        weight: 1,
    },
    department: {
        address: "",
        code: "11",
        divisionId: "010bf2da7a6e4cf1be48aa6f82c3a23f",
        grade: 1,
        id: "b99a7d2d123e49b5a7813cda66a450d6",
        name: "test11",
        parentId: "",
        phone: "",
    },
    precinct: {
        coordSystem: "BD09",
        divisionId: "test1",
        id: "1327568eb64a4cc6b53cd7d758976d03",
        latitude: 111,
        longitude: 111,
        name: "test11",
        number: "11",
        type: 1,
    },
};
